---
include:
  - board: soflelip_left
    shield: nice_view
  - board: soflelip_right
    shield: nice_view_custom
  - board: soflelip_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: soflelip_studio_left
  - board: soflelip_left
    shield: settings_reset
